export const modelData = [
  'Volkswagen',
  'Lexus',
  'Mazda',
  'Ford',
  'Nissan',
  'Hyundai',
  'Chevrolet',
  'Buick',
  'Volvo',
  'HUMMER',
  'Subaru',
  'Mercedes-Benz',
  'Mitsubishi',
  'Lincoln',
  'GMC',
  'MINI',
  'BMW',
  'Bentley',
  'Aston Martin',
  'Pontiac',
  'Lamborghini',
  'Audi',
  'Chrysler',
  'Kia',
  'Land Rover',
  'Toyota',
  'Honda',
];

export const priceData = [20, 30, 40, 50, 60, 70, 80];
